title: saviomd.com/blog
tagline: 'Blog sobre desenvolvimento front-end, design e etc'
url: http://saviomd.com/blog
baseurl: /blog
permalink: pretty
paginate: 10

author:
  name: 'Sávio Mendes'
  email: savio@saviomd.com

twitter: saviomd
dev: false
noindex: false
