title: saviomd.com/blog
tagline: 'Blog sobre desenvolvimento front-end, design e etc'
url: http://saviomd.com/blog
baseurl: /blog
permalink: pretty
paginate: 10

author:
  name: 'Sávio Mendes'
  email: savio@saviomd.com

themeColor: '#900'
twitter: saviomd
googleAnalyticsUA: 'UA-22412489-1'
minify: true
noindex: false
